# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSync < Formula
  desc "CLI to synchronize data from vault (hashicorp)"
  homepage "https://github.com/rca0/vault-sync"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rca0/vault-sync/releases/download/v1.0.0/vault-sync_1.0.0_darwin_amd64.tar.gz"
    sha256 "eb4485cb27085a43fa6aee67942b826d3743e166d5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rca0/vault-sync/releases/download/v1.0.1/vault-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "62e069db3067fdf2fa9d635b8808f6b6ae2933a721ef28ed7469da"
    end
  end

  def install
    bin.install "vault-sync"
  end

  test do
    system "#{bin}/vault-sync -v"
  end
end
