# This file was generated by GoReleaser. DO NOT EDIT.
class VaultSync < Formula
  desc "CLI to synchronize data from vault (hashicorp)"
  homepage "https://github.com/rca0/vault-sync"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/rca0/vault-sync/releases/download/v1.0.0/vault-sync_1.0.0_darwin_amd64.tar.gz"
    sha256 "dbaf53aaf61aa9524a839b8cda52efdc44926ac62f0f1332f2bdddcc29e41a7f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/rca0/vault-sync/releases/download/v1.0.1/vault-sync_1.0.0_linux_amd64.tar.gz"
      sha256 "f60235fb6502a76c1affb07dc692923a792d9e79a7db6e72dfd162b54e2b30c3"
    end
  end

  def install
    bin.install "vault-sync"
  end

  test do
    system "#{bin}/vault-sync -v"
  end
end
